"""Report generator — produces a multi-section Markdown report.

Each chapter is generated by an independent LLM call so context stays bounded.
Chapters are stitched together with the previous chapter's tail for coherence.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any
from collections.abc import Awaitable, Callable

from app.context.task_context import TaskContext

_SYSTEM_PROMPT_PATH = Path(__file__).resolve().parent.parent / "prompts" / "system_reporter.md"
TokenCallback = Callable[[str], Awaitable[None]]


class Reporter:
    def __init__(self, llm_client: Any):
        self.llm = llm_client
        self._system_prompt = self._load_system_prompt()

    async def generate(
        self,
        context: TaskContext,
        workspace: Any,
        *,
        stream_callback: TokenCallback | None = None,
        reasoning_callback: TokenCallback | None = None,
    ) -> str:
        """Generate the full report.  Returns Markdown text."""
        outline = (context.plan.report_outline if context.plan else None) or []
        if not outline:
            return self._assemble_simple_response(context, workspace)

        sections: list[str] = []
        if stream_callback:
            await self._emit(stream_callback, self._build_report_preamble(outline, context))

        for index, chapter in enumerate(outline):
            relevant_data = self._gather_data(chapter, context)
            prev_ending = sections[-1][-200:] if sections else ""
            prompt = self._build_section_prompt(
                context=context,
                chapter=chapter,
                chapter_index=index + 1,
                outline=outline,
                data=relevant_data,
                prev_ending=prev_ending,
            )
            if stream_callback:
                await self._emit(
                    stream_callback,
                    self._build_section_heading(index + 1, chapter),
                )
            section_text = await self._generate_section(prompt, stream_callback, reasoning_callback)
            sections.append(section_text)

        return self._assemble_full_report(sections, outline, context, workspace)

    async def _generate_section(
        self,
        prompt: str,
        stream_callback: TokenCallback | None,
        reasoning_callback: TokenCallback | None,
    ) -> str:
        stream = getattr(self.llm, "stream", None)
        if stream_callback and callable(stream):
            chunks: list[str] = []
            async for token in stream(
                prompt,
                max_tokens=3000,
                reasoning_callback=reasoning_callback,
            ):
                chunks.append(token)
                await self._emit(stream_callback, token)
            await self._emit(stream_callback, "\n")
            return "".join(chunks)

        section_text = await self.llm.call(
            prompt,
            max_tokens=3000,
            reasoning_callback=reasoning_callback,
        )
        await self._emit(stream_callback, section_text + "\n")
        return section_text

    async def _emit(self, callback: TokenCallback | None, text: str) -> None:
        if callback and text:
            await callback(text)

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_section_prompt(
        self,
        context: TaskContext,
        chapter: dict[str, Any],
        chapter_index: int,
        outline: list[dict[str, Any]],
        data: str,
        prev_ending: str,
    ) -> str:
        parts = [
            self._system_prompt,
            f"## 报告章节\n第{chapter_index}章：{chapter.get('title', '未命名')}",
            f"## 完整报告大纲\n{self._format_outline(outline)}",
            f"## 用户原始需求\n{context.user_query}",
            f"## 该章节的数据支撑\n{data}",
        ]
        if prev_ending:
            parts.append(f"## 上一章结尾（用于衔接）\n...{prev_ending}")

        word_count = chapter.get("word_count", 800)
        parts.append(f"## 写作要求\n- 约{word_count}字\n- 引用数据标注具体数值")

        # 质量校验警告
        warnings = self._relevant_warnings(chapter, context)
        if warnings:
            parts.append(f"## 需要在报告中说明的校验警告\n{warnings}")

        return "\n\n".join(parts)

    # ------------------------------------------------------------------
    # Data gathering
    # ------------------------------------------------------------------

    def _gather_data(self, chapter: dict[str, Any], context: TaskContext) -> str:
        """Collect step summaries and findings relevant to this chapter."""
        related_steps: list[str] = chapter.get("related_steps", [])
        pieces: list[str] = []

        if related_steps:
            for step_id in related_steps:
                summary = context.step_summaries.get(step_id)
                if summary:
                    pieces.append(f"### {step_id}\n{summary}")
        else:
            # No explicit mapping — include all summaries
            for step_id, summary in context.step_summaries.items():
                if step_id == "_history":
                    continue
                pieces.append(f"### {step_id}\n{summary}")

        if context.key_findings:
            pieces.append("### 关键发现\n" + "\n".join(f"- {f}" for f in context.key_findings))

        return "\n\n".join(pieces) if pieces else "（该章节暂无直接数据支撑）"

    def _relevant_warnings(self, chapter: dict[str, Any], context: TaskContext) -> str:
        related_steps = set(chapter.get("related_steps", []))
        lines: list[str] = []
        for qc in context.quality_checks:
            step_id = getattr(qc, "step_id", "")
            if related_steps and step_id not in related_steps:
                continue
            for w in getattr(qc, "warnings", []):
                if w:
                    lines.append(f"- [{step_id}] {w}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Assembly & post-processing
    # ------------------------------------------------------------------

    def _assemble_full_report(
        self,
        sections: list[str],
        outline: list[dict[str, Any]],
        context: TaskContext,
        workspace: Any,
    ) -> str:
        parts: list[str] = [self._build_report_preamble(outline, context)]
        final_answer_lines = self._final_answer_lines(context)
        if final_answer_lines:
            parts.append("## 最终答案\n" + "\n".join(final_answer_lines) + "\n")

        # Sections
        for i, (chapter, text) in enumerate(zip(outline, sections)):
            parts.append(f"{self._build_section_heading(i + 1, chapter)}{text.strip()}\n")

        # Inline chart references
        artifacts = context.artifact_manifest or []
        charts = [a for a in artifacts if a.get("kind") in ("chart", "image", "figure")]
        if charts:
            parts.append("## 图表\n")
            for chart in charts:
                desc = chart.get("description", chart.get("path", ""))
                path = chart.get("path", "")
                parts.append(f"![{desc}]({path})\n")

        # Attachment list
        attachments = self._list_attachments(workspace)
        if attachments:
            parts.append("## 附件\n")
            for att in attachments:
                parts.append(f"- [{att}]({att})")
            parts.append("")

        return "\n".join(parts)

    def _build_report_preamble(self, outline: list[dict[str, Any]], context: TaskContext) -> str:
        toc_lines = [f"{i+1}. {ch.get('title', '未命名')}" for i, ch in enumerate(outline)]
        return f"# 分析报告\n\n> 需求：{context.user_query}\n\n## 目录\n" + "\n".join(toc_lines) + "\n\n"

    def _build_section_heading(self, index: int, chapter: dict[str, Any]) -> str:
        title = chapter.get("title", "未命名")
        return f"## {index}. {title}\n\n"

    def _assemble_simple_response(self, context: TaskContext, workspace: Any) -> str:
        """Concise result-first response for non-report tasks."""
        parts = ["# 分析结果"]

        final_answer_lines = self._final_answer_lines(context)
        if final_answer_lines:
            parts.append("## 最终答案\n" + "\n".join(final_answer_lines))

        summary_lines = self._compact_summary_lines(context)
        if summary_lines:
            parts.append("## 简要结论\n" + "\n".join(f"- {line}" for line in summary_lines))
        else:
            parts.append("已完成处理，结果表和图表见下方。")

        attachments = self._list_attachments(workspace)
        if attachments:
            parts.append("## 附件\n" + "\n".join(f"- [{a}]({a})" for a in attachments) + "\n")

        return "\n\n".join(parts)

    def _final_answer_lines(self, context: TaskContext) -> list[str]:
        answers = getattr(context, "final_answers", {}) or {}
        if not answers:
            return []
        lines = []
        multiple = len(answers) > 1
        for step_id, answer in answers.items():
            answer_text = " ".join(str(answer).strip().split())
            if not answer_text:
                continue
            prefix = f"{step_id}: " if multiple else ""
            lines.append(f"Final Answer: {prefix}{answer_text}")
        return lines

    def _compact_summary_lines(self, context: TaskContext, max_lines: int = 4) -> list[str]:
        lines: list[str] = []
        final_answer_lines = set(self._final_answer_lines(context))
        for finding in context.key_findings:
            clean = self._clean_summary_line(str(finding))
            if clean and clean not in final_answer_lines:
                lines.append(clean)
            if len(lines) >= max_lines:
                return lines

        for step_id, summary in context.step_summaries.items():
            if step_id == "_history":
                continue
            for raw_line in str(summary).splitlines():
                clean = self._clean_summary_line(raw_line)
                if not clean:
                    continue
                if clean in final_answer_lines:
                    continue
                lines.append(clean)
                if len(lines) >= max_lines:
                    return lines
        return lines

    def _clean_summary_line(self, line: str) -> str:
        clean = " ".join(line.strip().split())
        if not clean:
            return ""
        lowered = clean.lower()
        noisy_tokens = (
            "output/",
            "normalized/",
            ".parquet",
            ".xlsx",
            ".csv",
            "保存",
            "导出",
            "文件",
            "path",
        )
        if any(token in lowered for token in noisy_tokens):
            return ""
        if len(clean) > 220:
            clean = clean[:217].rstrip() + "..."
        return clean

    def _list_attachments(self, workspace: Any) -> list[str]:
        try:
            return workspace.list_output_files()
        except Exception:
            return []

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _format_outline(self, outline: list[dict[str, Any]]) -> str:
        return "\n".join(
            f"{i+1}. {ch.get('title', '未命名')}" for i, ch in enumerate(outline)
        )

    def _load_system_prompt(self) -> str:
        if _SYSTEM_PROMPT_PATH.exists():
            return _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
        return "你正在撰写数据分析报告的一个章节。行文专业、条理清晰，引用数据标注具体数值。"
