"""Report generator — produces a multi-section Markdown report.

Each chapter is generated by an independent LLM call so context stays bounded.
Chapters are stitched together with the previous chapter's tail for coherence.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.context.task_context import TaskContext

_SYSTEM_PROMPT_PATH = Path(__file__).resolve().parent.parent / "prompts" / "system_reporter.md"


class Reporter:
    def __init__(self, llm_client: Any):
        self.llm = llm_client
        self._system_prompt = self._load_system_prompt()

    async def generate(self, context: TaskContext, workspace: Any) -> str:
        """Generate the full report.  Returns Markdown text."""
        outline = (context.plan.report_outline if context.plan else None) or []
        if not outline:
            return self._assemble_simple_response(context, workspace)

        sections: list[str] = []
        for index, chapter in enumerate(outline):
            relevant_data = self._gather_data(chapter, context)
            prev_ending = sections[-1][-200:] if sections else ""
            prompt = self._build_section_prompt(
                context=context,
                chapter=chapter,
                chapter_index=index + 1,
                outline=outline,
                data=relevant_data,
                prev_ending=prev_ending,
            )
            section_text = await self.llm.call(prompt, max_tokens=3000)
            sections.append(section_text)

        return self._assemble_full_report(sections, outline, context, workspace)

    # ------------------------------------------------------------------
    # Prompt construction
    # ------------------------------------------------------------------

    def _build_section_prompt(
        self,
        context: TaskContext,
        chapter: dict[str, Any],
        chapter_index: int,
        outline: list[dict[str, Any]],
        data: str,
        prev_ending: str,
    ) -> str:
        parts = [
            self._system_prompt,
            f"## 报告章节\n第{chapter_index}章：{chapter.get('title', '未命名')}",
            f"## 完整报告大纲\n{self._format_outline(outline)}",
            f"## 用户原始需求\n{context.user_query}",
            f"## 该章节的数据支撑\n{data}",
        ]
        if prev_ending:
            parts.append(f"## 上一章结尾（用于衔接）\n...{prev_ending}")

        word_count = chapter.get("word_count", 800)
        parts.append(f"## 写作要求\n- 约{word_count}字\n- 引用数据标注具体数值")

        # 质量校验警告
        warnings = self._relevant_warnings(chapter, context)
        if warnings:
            parts.append(f"## 需要在报告中说明的校验警告\n{warnings}")

        return "\n\n".join(parts)

    # ------------------------------------------------------------------
    # Data gathering
    # ------------------------------------------------------------------

    def _gather_data(self, chapter: dict[str, Any], context: TaskContext) -> str:
        """Collect step summaries and findings relevant to this chapter."""
        related_steps: list[str] = chapter.get("related_steps", [])
        pieces: list[str] = []

        if related_steps:
            for step_id in related_steps:
                summary = context.step_summaries.get(step_id)
                if summary:
                    pieces.append(f"### {step_id}\n{summary}")
        else:
            # No explicit mapping — include all summaries
            for step_id, summary in context.step_summaries.items():
                if step_id == "_history":
                    continue
                pieces.append(f"### {step_id}\n{summary}")

        if context.key_findings:
            pieces.append("### 关键发现\n" + "\n".join(f"- {f}" for f in context.key_findings))

        return "\n\n".join(pieces) if pieces else "（该章节暂无直接数据支撑）"

    def _relevant_warnings(self, chapter: dict[str, Any], context: TaskContext) -> str:
        related_steps = set(chapter.get("related_steps", []))
        lines: list[str] = []
        for qc in context.quality_checks:
            step_id = getattr(qc, "step_id", "")
            if related_steps and step_id not in related_steps:
                continue
            for w in getattr(qc, "warnings", []):
                if w:
                    lines.append(f"- [{step_id}] {w}")
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Assembly & post-processing
    # ------------------------------------------------------------------

    def _assemble_full_report(
        self,
        sections: list[str],
        outline: list[dict[str, Any]],
        context: TaskContext,
        workspace: Any,
    ) -> str:
        parts: list[str] = []

        # Title
        parts.append(f"# 分析报告\n\n> 需求：{context.user_query}\n")

        # Table of contents
        toc_lines = [f"{i+1}. {ch.get('title', '未命名')}" for i, ch in enumerate(outline)]
        parts.append("## 目录\n" + "\n".join(toc_lines) + "\n")

        # Sections
        for i, (chapter, text) in enumerate(zip(outline, sections)):
            title = chapter.get("title", "未命名")
            parts.append(f"## {i+1}. {title}\n\n{text.strip()}\n")

        # Inline chart references
        artifacts = context.artifact_manifest or []
        charts = [a for a in artifacts if a.get("kind") in ("chart", "image", "figure")]
        if charts:
            parts.append("## 图表\n")
            for chart in charts:
                desc = chart.get("description", chart.get("path", ""))
                path = chart.get("path", "")
                parts.append(f"![{desc}]({path})\n")

        # Attachment list
        attachments = self._list_attachments(workspace)
        if attachments:
            parts.append("## 附件\n")
            for att in attachments:
                parts.append(f"- [{att}]({att})")
            parts.append("")

        return "\n".join(parts)

    def _assemble_simple_response(self, context: TaskContext, workspace: Any) -> str:
        """Fallback when no report_outline is defined."""
        parts = [f"# 分析结果\n\n> 需求：{context.user_query}\n"]

        for step_id, summary in context.step_summaries.items():
            if step_id == "_history":
                continue
            parts.append(f"### {step_id}\n{summary}\n")

        if context.key_findings:
            parts.append("### 关键发现\n" + "\n".join(f"- {f}" for f in context.key_findings) + "\n")

        attachments = self._list_attachments(workspace)
        if attachments:
            parts.append("## 附件\n" + "\n".join(f"- [{a}]({a})" for a in attachments) + "\n")

        return "\n".join(parts)

    def _list_attachments(self, workspace: Any) -> list[str]:
        try:
            return workspace.list_output_files()
        except Exception:
            return []

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _format_outline(self, outline: list[dict[str, Any]]) -> str:
        return "\n".join(
            f"{i+1}. {ch.get('title', '未命名')}" for i, ch in enumerate(outline)
        )

    def _load_system_prompt(self) -> str:
        if _SYSTEM_PROMPT_PATH.exists():
            return _SYSTEM_PROMPT_PATH.read_text(encoding="utf-8").strip()
        return "你正在撰写数据分析报告的一个章节。行文专业、条理清晰，引用数据标注具体数值。"
